# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridematch', '0002_auto_20170325_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerevent',
            name='time',
        ),
        migrations.AddField(
            model_name='passengerevent',
            name='email',
            field=models.EmailField(default='johndoe@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
